(ns qa.cljfx-shell
  "Executable QA suites mapped to qa/procedures/*.qa.md.
  Drives the live JavaFX app through stella.qa.ui-driver only."
  (:require [cljfx.api :as fx]
            [stella.qa.args :as qa-args]
            [stella.qa.auto-close :as qa-auto-close]
            [stella.qa.ui-driver :as ui])
  (:import [javafx.stage Stage Window]))

(defn- fail! [message]
  (binding [*out* *err*]
    (println "QA FAIL:" message))
  (System/exit 1))

(defn- pass! [suite message]
  (println (str "QA PASS [" suite "]: " message)))

(defn- run-suite! [suite-name thunk]
  (println (str "QA SUITE: " suite-name))
  (try
    (thunk)
    (println (str "QA SUITE PASS: " suite-name))
    (catch Throwable t
      (fail! (str suite-name " - " (.getMessage t))))))

(defn- with-app! [{:keys [hard-exit? width height] :as opts} f]
  (let [done (promise)]
    (fx/on-fx-thread
      (try
        (ui/launch-app! :width width :height height :hard-exit? hard-exit?)
        (if-let [^Stage stage (ui/wait-for-stage 50)]
          (try
            (f stage)
            (deliver done :ok)
            (finally
              (ui/ensure-app-closed! stage)))
          (do (fail! "Timed out waiting for Stella window")
              (deliver done :error)))
        (catch Throwable t
          (fail! (.getMessage t))
          (deliver done :error))))
    (case (deref done 120000 :timeout)
      :ok nil
      (fail! "QA app session timed out"))))

(defn- run-qa-auto-close! []
  (when-not (= "5" (System/getProperty "stella.qa.auto-close-seconds"))
    (fail! "qa-auto-close suite requires --qa 5"))
  (let [started (promise)]
    (fx/on-fx-thread
      (try
        (ui/launch-app!)
        (deliver started :ok)
        (catch Throwable t
          (fail! (.getMessage t))
          (deliver started :error))))
    (case (deref started 30000 :timeout)
      :ok nil
      (fail! "Failed to launch Stella")))
  (when-not (ui/wait-for-stage 50)
    (fail! "Timed out waiting for Stella window"))
  (when-not (= "Stella" (ui/window-title (ui/main-stage)))
    (fail! (str "Window title is " (ui/window-title (ui/main-stage)))))
  (pass! "qa-auto-close" "Window title is Stella")
  (let [deadline (+ (System/currentTimeMillis) 10000)]
    (loop []
      (when (and (< (System/currentTimeMillis) deadline)
                 (ui/main-stage))
        (Thread/sleep 100)
        (recur)))
    (when (ui/main-stage)
      (fail! "Stella window still visible after auto-close timeout")))
  (pass! "qa-auto-close" "Application closed without manual quit"))

(defn- run-shell-launch! []
  (with-app! {}
    (fn [^Stage stage]
      (when-not (= "Stella" (ui/window-title stage))
        (fail! (str "Window title is " (ui/window-title stage))))
      (pass! "shell-launch" "Window title is Stella")
      (when-not (= ["File" "Edit" "View" "Help"] (ui/top-level-menu-labels stage))
        (fail! (str "Unexpected menus: " (ui/top-level-menu-labels stage))))
      (pass! "shell-launch" "Top-level menus are visible")
      (when-not (ui/region-bounds stage :canvas)
        (fail! "Canvas region :canvas is not visible"))
      (pass! "shell-launch" "Diagram canvas region is visible")
      (ui/quit-app! stage)
      (pass! "shell-launch" "File → Quit requested"))))

(defn- run-shell-menus! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/open-menu! stage "File")
      (when-not (ui/menu-item-disabled? stage "File" "New")
        (fail! "New should be disabled"))
      (pass! "shell-menus" "New is disabled")
      (when (ui/menu-item-disabled? stage "File" "Quit")
        (fail! "Quit should be enabled"))
      (pass! "shell-menus" "Quit is enabled")
      (ui/close-menus! stage)
      (ui/open-menu! stage "Help")
      (when (ui/menu-item-disabled? stage "Help" "About Stella")
        (fail! "About Stella should be enabled"))
      (pass! "shell-menus" "About Stella is enabled")
      (ui/close-menus! stage)
      (ui/quit-app! stage)
      (pass! "shell-menus" "Quit requested"))))

(defn- run-shell-about! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/menu-choose! stage "Help" "About Stella")
      (loop [n 20]
        (if (ui/dialog-visible? "diagram editor")
          nil
          (when (pos? n)
            (Thread/sleep 100)
            (recur (dec n)))))
      (when-not (ui/dialog-visible? "diagram editor")
        (fail! "About dialog did not appear"))
      (pass! "shell-about" "About dialog text is visible")
      (when-not (= "About Stella" (ui/frontmost-dialog-title))
        (fail! (str "Unexpected front dialog: " (ui/frontmost-dialog-title))))
      (pass! "shell-about" "About dialog is frontmost")
      (ui/click-ok-on-front-dialog!)
      (Thread/sleep 200)
      (when (ui/dialog-visible? "diagram editor")
        (ui/close-menus! stage))
      (when (ui/dialog-visible? "diagram editor")
        (fail! "About dialog did not dismiss"))
      (pass! "shell-about" "About dialog dismissed")
      (when-not (= "Stella" (ui/window-title stage))
        (fail! "Main window title changed after About"))
      (pass! "shell-about" "Main window remains open")
      (ui/quit-app! stage)
      (pass! "shell-about" "Quit requested"))))

(defn- run-shell-resize! []
  (with-app! {:width 800 :height 600}
    (fn [^Stage stage]
      (when-not (ui/region-bounds stage :canvas)
        (fail! "Canvas region is not visible"))
      (pass! "shell-resize" "Canvas visible before resize")
      (let [w0 (.getWidth stage)
            h0 (.getHeight stage)]
        (ui/resize-window! stage 950 700)
        (Thread/sleep 500)
        (when-not (ui/region-bounds stage :canvas)
          (fail! "Canvas region missing after resize"))
        (when-not (and (> (.getWidth stage) w0) (> (.getHeight stage) h0))
          (fail! (str "Window did not grow: " w0 "x" h0 " -> "
                      (.getWidth stage) "x" (.getHeight stage))))
        (pass! "shell-resize" "Window and canvas region grew after resize")
        (ui/click-in-region! stage :canvas :center)
        (pass! "shell-resize" "Canvas center click succeeded")
        (when-not (= "Stella" (ui/window-title stage))
          (fail! "Main window closed after canvas click"))
        (pass! "shell-resize" "Main window still showing")
        (ui/quit-app! stage)
        (pass! "shell-resize" "Quit requested")))))

(defn- run-shell-quit! []
  (with-app! {}
    (fn [^Stage stage]
      (when-not (.isShowing stage)
        (fail! "Main window is not visible"))
      (pass! "shell-quit" "Main window is visible")
      (ui/menu-choose! stage "File" "Quit")
      (Thread/sleep 200)
      (when (.isShowing stage)
        (fail! "Main window still visible after Quit"))
      (pass! "shell-quit" "File → Quit closes the window")
      (System/exit 0))))

(defn- run-place-stock! []
  (with-app! {}
    (fn [^Stage stage]
      (when-not (ui/region-bounds stage :canvas)
        (fail! "Canvas region :canvas is not visible"))
      (pass! "place-stock" "Canvas region is visible")
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1")
        (fail! "Stock1 did not appear"))
      (when-not (ui/element-shows? stage :stock "Stock1" "Stock1")
        (fail! "Stock1 name not visible"))
      (when-not (ui/element-shows? stage :stock "Stock1" "0")
        (fail! "Stock1 initial value not visible"))
      (pass! "place-stock" "Stock1 placed with name and value 0")
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas [100 50])
      (when-not (ui/wait-for-element! stage :stock "Stock2")
        (fail! "Stock2 did not appear"))
      (when-not (ui/element-shows? stage :stock "Stock2" "Stock2")
        (fail! "Stock2 name not visible"))
      (when-not (ui/element-shows? stage :stock "Stock2" "0")
        (fail! "Stock2 initial value not visible"))
      (pass! "place-stock" "Stock2 placed with name and value 0")
      (ui/quit-app! stage)
      (pass! "place-stock" "Quit requested"))))

(defn- place-two-stocks! [^Stage stage]
  (ui/click-palette! stage "Stock")
  (ui/click-in-region! stage :canvas :center)
  (when-not (ui/wait-for-element! stage :stock "Stock1")
    (fail! "Stock1 not placed"))
  (ui/click-palette! stage "Stock")
  (ui/click-in-region! stage :canvas [150 50])
  (when-not (ui/wait-for-element! stage :stock "Stock2")
    (fail! "Stock2 not placed")))

(defn- assert-flow! [^Stage stage flow-name from-name to-name & {:keys [suite show-name?]
                                                                 :or {show-name? true}}]
  (when-not (ui/wait-for-element! stage :flow flow-name)
    (fail! (str flow-name " did not appear")))
  (when show-name?
    (when-not (ui/element-shows? stage :flow flow-name flow-name)
      (fail! (str flow-name " name not visible"))))
  (when-not (ui/element-shows? stage :flow flow-name "0")
    (fail! (str flow-name " rate not visible")))
  (when-not (ui/flow-directed? stage from-name to-name)
    (fail! (str flow-name " direction from " from-name " to " to-name " not visible")))
  (when suite
    (pass! suite (str flow-name " connects " from-name " to " to-name
                      (when show-name? " with rate 0")))))

(defn- run-connect-flow! []
  (with-app! {}
    (fn [^Stage stage]
      (place-two-stocks! stage)
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :stock "Stock2")
      (assert-flow! stage "Flow1" "Stock1" "Stock2" :suite "connect-flow")
      (ui/quit-app! stage)
      (pass! "connect-flow" "Quit requested"))))

(defn- run-cloud-palette! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Source")
      (when-not (ui/wait-for-palette-tool-active! "Source")
        (fail! "Source palette not active after arming"))
      (when (ui/palette-tool-active? "Sink")
        (fail! "Sink palette active while Source armed"))
      (pass! "cloud-palette" "Source armed and highlighted")
      (ui/click-in-region! stage :canvas [-150 0])
      (when-not (ui/wait-for-element! stage :source "Source1")
        (fail! "Source1 did not appear"))
      (pass! "cloud-palette" "Source1 placed")
      (when-not (ui/wait-for-no-palette-tool-active!)
        (fail! "Palette still active after placing Source1"))
      (pass! "cloud-palette" "Palette disarmed after Source placement")
      (ui/click-palette! stage "Sink")
      (when-not (ui/wait-for-palette-tool-active! "Sink")
        (fail! "Sink palette not active after arming"))
      (pass! "cloud-palette" "Sink armed and highlighted")
      (ui/click-in-region! stage :canvas [150 0])
      (when-not (ui/wait-for-element! stage :sink "Sink1")
        (fail! "Sink1 did not appear"))
      (pass! "cloud-palette" "Sink1 placed")
      (when-not (ui/wait-for-no-palette-tool-active!)
        (fail! "Palette still active after placing Sink1"))
      (pass! "cloud-palette" "Palette disarmed after first Sink placement")
      (ui/click-palette! stage "Sink")
      (ui/click-in-region! stage :canvas [200 40])
      (when-not (ui/wait-for-element! stage :sink "Sink2")
        (fail! "Sink2 did not appear"))
      (pass! "cloud-palette" "Sink2 placed after re-arming Sink")
      (when-not (ui/wait-for-no-palette-tool-active!)
        (fail! "Palette still active after placing Sink2"))
      (pass! "cloud-palette" "Palette disarmed after second Sink placement")
      (ui/quit-app! stage)
      (pass! "cloud-palette" "Quit requested"))))

(defn- run-cloud-endpoints! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Source")
      (ui/click-in-region! stage :canvas [-150 0])
      (when-not (ui/wait-for-element! stage :source "Source1")
        (fail! "Source1 did not appear"))
      (pass! "cloud-endpoints" "Source1 placed")
      (ui/click-palette! stage "Sink")
      (ui/click-in-region! stage :canvas [150 0])
      (when-not (ui/wait-for-element! stage :sink "Sink1")
        (fail! "Sink1 did not appear"))
      (pass! "cloud-endpoints" "Sink1 placed")
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1")
        (fail! "Stock1 did not appear"))
      (pass! "cloud-endpoints" "Stock1 placed")
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :source "Source1")
      (ui/click-element! stage :stock "Stock1")
      (assert-flow! stage "Flow1" "Source1" "Stock1"
                    :suite "cloud-endpoints" :show-name? false)
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :sink "Sink1")
      (assert-flow! stage "Flow2" "Stock1" "Sink1"
                    :suite "cloud-endpoints" :show-name? false)
      (ui/quit-app! stage)
      (pass! "cloud-endpoints" "Quit requested"))))

(defn- run-connectors! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas [-100 0])
      (when-not (ui/wait-for-element! stage :stock "Stock1")
        (fail! "Stock1 not placed"))
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas [100 0])
      (when-not (ui/wait-for-element! stage :stock "Stock2")
        (fail! "Stock2 not placed"))
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :stock "Stock2")
      (assert-flow! stage "Flow1" "Stock1" "Stock2" :suite "connectors")
      (ui/click-palette! stage "Converter")
      (ui/click-in-region! stage :canvas [0 100])
      (when-not (ui/wait-for-element! stage :converter "Converter1")
        (fail! "Converter1 did not appear"))
      (when-not (ui/element-shows? stage :converter "Converter1" "Converter1")
        (fail! "Converter1 name not visible"))
      (when (ui/element-icon-label-equals? stage :converter "Converter1" "0")
        (fail! "Converter1 value shown on icon"))
      (pass! "connectors" "Converter1 placed with name only")
      (ui/click-palette! stage "Connector")
      (ui/click-element! stage :converter "Converter1")
      (ui/click-element! stage :flow "Flow1")
      (when-not (ui/wait-for-element! stage :connector "Connector1")
        (fail! "Connector1 did not appear"))
      (pass! "connectors" "Connector1 connects Converter1 to Flow1")
      (ui/click-palette! stage "Connector")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :converter "Converter1")
      (when-not (ui/wait-for-element! stage :connector "Connector2")
        (fail! "Connector2 did not appear"))
      (when-not (ui/connector-directed? stage :stock "Stock1" :converter "Converter1")
        (fail! "Connector2 direction from Stock1 to Converter1 not visible"))
      (pass! "connectors" "Connector2 connects Stock1 to Converter1")
      (ui/quit-app! stage)
      (pass! "connectors" "Quit requested"))))

(defn- run-edit-stock! []
  (with-app! {}
    (fn [^Stage stage]
      (when-not (ui/region-bounds stage :canvas)
        (fail! "Canvas region :canvas is not visible"))
      (pass! "edit-stock" "Canvas region is visible")
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1")
        (fail! "Stock1 did not appear"))
      (when-not (ui/element-shows? stage :stock "Stock1" "Stock1")
        (fail! "Stock1 name not visible"))
      (when-not (ui/element-shows? stage :stock "Stock1" "0")
        (fail! "Stock1 minimum not visible"))
      (ui/right-click-element! stage :stock "Stock1")
      (when-not (ui/wait-for-dialog! "Edit Stock" :attempts 50)
        (fail! "Edit Stock dialog did not appear"))
      (ui/type-into-dialog-field! "Name" "Cats")
      (ui/click-ok-on-dialog! "Edit Stock")
      (when-not (ui/wait-for-element! stage :stock "Cats")
        (fail! "Cats did not appear after rename"))
      (when-not (ui/element-shows? stage :stock "Cats" "Cats")
        (fail! "Cats name not visible"))
      (when-not (ui/element-shows? stage :stock "Cats" "0")
        (fail! "Cats minimum not visible"))
      (pass! "edit-stock" "Stock renamed to Cats")
      (ui/right-click-element! stage :stock "Cats")
      (when-not (ui/wait-for-dialog! "Edit Stock")
        (fail! "Edit Stock dialog did not reappear"))
      (ui/type-into-dialog-field! "Initial value" "25")
      (ui/type-into-dialog-field! "Minimum" "5")
      (ui/type-into-dialog-field! "Maximum" "100")
      (ui/click-ok-on-dialog! "Edit Stock")
      (when-not (ui/element-shows? stage :stock "Cats" "Cats")
        (fail! "Cats name missing after bounds edit"))
      (when-not (ui/element-shows? stage :stock "Cats" "5")
        (fail! "Cats minimum not visible after edit"))
      (when-not (ui/element-shows? stage :stock "Cats" "100")
        (fail! "Cats maximum not visible after edit"))
      (when-not (ui/element-not-shows? stage :stock "Cats" "25")
        (fail! "Initial value 25 shown on icon"))
      (pass! "edit-stock" "Cats bounds updated; initial value not on icon")
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas [120 40])
      (when-not (ui/wait-for-element! stage :stock "Stock2")
        (fail! "Stock2 did not appear"))
      (ui/right-click-element! stage :stock "Cats")
      (when-not (ui/wait-for-dialog! "Edit Stock")
        (fail! "Edit Stock dialog missing for duplicate rename"))
      (ui/type-into-dialog-field! "Name" "Stock2")
      (ui/click-ok-on-dialog! "Edit Stock")
      (when-not (ui/element-visible? stage :stock "Cats")
        (fail! "Cats disappeared after rejected duplicate rename"))
      (when-not (ui/element-visible? stage :stock "Stock2")
        (fail! "Stock2 missing after rejected duplicate rename"))
      (pass! "edit-stock" "Duplicate rename rejected")
      (ui/quit-app! stage)
      (pass! "edit-stock" "Quit requested"))))

(defn- run-edit-flow! []
  (with-app! {}
    (fn [^Stage stage]
      (place-two-stocks! stage)
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :stock "Stock2")
      (assert-flow! stage "Flow1" "Stock1" "Stock2" :suite "edit-flow")
      (ui/right-click-element! stage :flow "Flow1")
      (when-not (ui/wait-for-dialog! "Edit Flow" :attempts 50)
        (fail! "Edit Flow dialog did not appear"))
      (ui/type-into-dialog-field! "Name" "Drain")
      (ui/type-into-dialog-field! "Rate" "5")
      (ui/click-ok-on-dialog! "Edit Flow")
      (when-not (ui/wait-for-element! stage :flow "Drain")
        (fail! "Drain did not appear after rename"))
      (when-not (ui/element-shows? stage :flow "Drain" "Drain")
        (fail! "Drain name not visible"))
      (when-not (ui/element-shows? stage :flow "Drain" "5")
        (fail! "Drain rate not visible"))
      (when-not (ui/flow-pipe-thicker-than-connector? stage)
        (fail! "Flow pipe is not thicker than connector arrows"))
      (pass! "edit-flow" "Flow renamed to Drain with rate 5")
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock2")
      (ui/click-element! stage :stock "Stock1")
      (when-not (ui/wait-for-element! stage :flow "Flow2")
        (fail! "Flow2 did not appear"))
      (ui/right-click-element! stage :flow "Drain")
      (when-not (ui/wait-for-dialog! "Edit Flow")
        (fail! "Edit Flow dialog missing for duplicate rename"))
      (ui/type-into-dialog-field! "Name" "Flow2")
      (ui/click-ok-on-dialog! "Edit Flow")
      (when-not (ui/element-visible? stage :flow "Drain")
        (fail! "Drain disappeared after rejected duplicate rename"))
      (when-not (ui/element-visible? stage :flow "Flow2")
        (fail! "Flow2 missing after rejected duplicate rename"))
      (pass! "edit-flow" "Duplicate rename rejected")
      (ui/right-click-element! stage :flow "Drain")
      (when-not (ui/wait-for-dialog! "Edit Flow")
        (fail! "Edit Flow dialog missing for empty rate test"))
      (ui/clear-dialog-field! "Rate")
      (ui/click-ok-on-dialog! "Edit Flow")
      (when-not (ui/element-shows? stage :flow "Drain" "5")
        (fail! "Drain rate changed after empty rate rejected"))
      (pass! "edit-flow" "Empty rate rejected")
      (ui/quit-app! stage)
      (pass! "edit-flow" "Quit requested"))))

(defn- run-edit-converter! []
  (with-app! {}
    (fn [^Stage stage]
      (place-two-stocks! stage)
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :stock "Stock2")
      (assert-flow! stage "Flow1" "Stock1" "Stock2" :suite "edit-converter")
      (ui/click-palette! stage "Converter")
      (ui/click-in-region! stage :canvas [-50 80])
      (when-not (ui/wait-for-element! stage :converter "Converter1" :attempts 20)
        (fail! "Converter1 did not appear"))
      (when-not (ui/element-shows? stage :converter "Converter1" "Converter1")
        (fail! "Converter1 name not visible"))
      (when (ui/element-icon-label-equals? stage :converter "Converter1" "0")
        (fail! "Converter1 value shown on icon"))
      (ui/click-palette! stage "Connector")
      (ui/click-element! stage :converter "Converter1")
      (ui/click-element! stage :flow "Flow1")
      (when-not (ui/wait-for-element! stage :connector "Connector1" :attempts 20)
        (fail! "Connector1 did not appear"))
      (ui/right-click-element! stage :converter "Converter1")
      (when-not (ui/wait-for-dialog! "Edit Converter" :attempts 50)
        (fail! "Edit Converter dialog did not appear"))
      (ui/type-into-dialog-field! "Name" "Growth")
      (ui/type-into-dialog-field! "Formula" "Stock1 * 0.1")
      (ui/click-ok-on-dialog! "Edit Converter")
      (when-not (ui/wait-for-element! stage :converter "Growth" :attempts 20)
        (fail! "Growth did not appear after rename"))
      (when-not (ui/element-shows? stage :converter "Growth" "Growth")
        (fail! "Growth name not visible"))
      (when-not (ui/connector-canvas-formula? "Connector1" "Stock1 * 0.1")
        (fail! "Connector1 formula not on canvas"))
      (pass! "edit-converter" "Converter renamed to Growth with formula on connector")
      (ui/click-palette! stage "Converter")
      (ui/click-in-region! stage :canvas [200 80])
      (when-not (ui/wait-for-element! stage :converter "Converter2" :attempts 20)
        (fail! "Converter2 did not appear"))
      (ui/right-click-element! stage :converter "Growth")
      (when-not (ui/wait-for-dialog! "Edit Converter")
        (fail! "Edit Converter dialog missing for duplicate rename"))
      (ui/type-into-dialog-field! "Name" "Converter2")
      (ui/click-ok-on-dialog! "Edit Converter")
      (when-not (ui/element-visible? stage :converter "Growth")
        (fail! "Growth disappeared after rejected duplicate rename"))
      (pass! "edit-converter" "Duplicate rename rejected")
      (ui/right-click-element! stage :converter "Converter2")
      (when-not (ui/wait-for-dialog! "Edit Converter")
        (fail! "Edit Converter dialog missing for formula without link"))
      (ui/type-into-dialog-field! "Formula" "Stock1 * 0.2")
      (ui/click-ok-on-dialog! "Edit Converter")
      (when-not (ui/element-shows? stage :converter "Converter2" "Converter2")
        (fail! "Converter2 name not visible"))
      (when (ui/element-icon-label-equals? stage :converter "Converter2" "Stock1 * 0.2")
        (fail! "Formula shown on converter without flow link"))
      (pass! "edit-converter" "Formula without flow link rejected")
      (ui/quit-app! stage)
      (pass! "edit-converter" "Quit requested"))))

(defn- run-drag-stock! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1" :attempts 20)
        (fail! "Stock1 did not appear"))
      (ui/press-escape! stage)
      (let [initial-bounds (ui/element-bounds stage :stock "Stock1")]
        (ui/drag-element! stage :stock "Stock1" :canvas [120 60])
        (when-not (ui/wait-for-bounds-change! stage :stock "Stock1" initial-bounds :attempts 20)
          (fail! "Stock1 bounds did not change after drag"))
        (when-not (ui/element-visible? stage :stock "Stock1")
          (fail! "Stock1 not visible after drag"))
        (when-not (= 1 (ui/diagram-stock-count stage))
          (fail! "Expected exactly one stock after drag"))
        (pass! "drag-stock" "Stock1 dragged to new position")
        (ui/click-palette! stage "Stock")
        (ui/click-in-region! stage :canvas [200 40])
        (when-not (ui/wait-for-element! stage :stock "Stock2" :attempts 20)
          (fail! "Stock2 did not appear"))
        (ui/click-palette! stage "Flow")
        (ui/click-element! stage :stock "Stock1")
        (ui/click-element! stage :stock "Stock2")
        (assert-flow! stage "Flow1" "Stock1" "Stock2" :suite "drag-stock")
        (ui/press-escape! stage)
        (let [stock2-before (ui/element-bounds stage :stock "Stock2")]
          (ui/drag-element! stage :stock "Stock1" :canvas [40 -20])
          (Thread/sleep 300)
          (when-not (ui/flow-directed? stage "Stock1" "Stock2")
            (fail! "Flow1 not directed from Stock1 to Stock2 after drag"))
          (when-not (ui/element-visible? stage :stock "Stock2")
            (fail! "Stock2 missing after Stock1 drag"))
          (when-not (ui/bounds-unchanged? stage :stock "Stock2" stock2-before)
            (fail! "Stock2 moved when only Stock1 was dragged"))
          (pass! "drag-stock" "Flow follows dragged Stock1; Stock2 unchanged"))
        (ui/click-palette! stage "Stock")
        (let [stock2-armed-before (ui/element-bounds stage :stock "Stock2")]
          (ui/drag-element! stage :stock "Stock2" :canvas :center)
          (Thread/sleep 300)
          (when-not (ui/bounds-unchanged? stage :stock "Stock2" stock2-armed-before)
            (fail! "Stock2 moved while placement tool armed"))
          (pass! "drag-stock" "Drag disabled while placement armed"))
        (ui/quit-app! stage)
        (pass! "drag-stock" "Quit requested")))))

(defn- wait-for-element-gone!
  [^Stage stage kind name & {:keys [attempts] :or {attempts 20}}]
  (loop [n attempts]
    (if (ui/element-visible? stage kind name)
      (when (pos? n)
        (Thread/sleep 100)
        (recur (dec n)))
      true)))

(defn- run-delete-selection! []
  (with-app! {}
    (fn [^Stage stage]
      (place-two-stocks! stage)
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :stock "Stock2")
      (when-not (ui/wait-for-element! stage :flow "Flow1" :attempts 20)
        (fail! "Flow1 did not appear"))
      (pass! "delete-selection" "Flow1 connects Stock1 to Stock2")
      (ui/press-escape! stage)
      (ui/click-element! stage :stock "Stock1")
      (when-not (ui/element-selected? stage :stock "Stock1")
        (fail! "Stock1 not selected before delete"))
      (ui/press-delete! stage)
      (when-not (wait-for-element-gone! stage :stock "Stock1")
        (fail! "Stock1 still visible after delete"))
      (when-not (wait-for-element-gone! stage :flow "Flow1")
        (fail! "Flow1 still visible after stock delete cascade"))
      (when-not (ui/wait-for-element! stage :stock "Stock2")
        (fail! "Stock2 missing after delete"))
      (pass! "delete-selection" "Delete removes selected stock and attached flow")
      (ui/click-palette! stage "Converter")
      (ui/click-in-region! stage :canvas [-60 100])
      (when-not (ui/wait-for-element! stage :converter "Converter1" :attempts 20)
        (fail! "Converter1 did not appear"))
      (ui/click-palette! stage "Connector")
      (ui/click-element! stage :stock "Stock2")
      (ui/click-element! stage :converter "Converter1")
      (when-not (ui/wait-for-element! stage :connector "Connector1" :attempts 20)
        (fail! "Connector1 did not appear"))
      (pass! "delete-selection" "Connector1 links Stock2 to Converter1")
      (ui/press-escape! stage)
      (ui/click-element! stage :converter "Converter1")
      (when-not (ui/element-selected? stage :converter "Converter1")
        (fail! "Converter1 not selected before backspace"))
      (ui/press-backspace! stage)
      (when-not (wait-for-element-gone! stage :converter "Converter1")
        (fail! "Converter1 still visible after backspace"))
      (when-not (wait-for-element-gone! stage :connector "Connector1")
        (fail! "Connector1 still visible after converter delete cascade"))
      (when-not (ui/wait-for-element! stage :stock "Stock2")
        (fail! "Stock2 missing after converter delete"))
      (pass! "delete-selection" "Backspace removes converter and attached connector")
      (ui/click-palette! stage "Flow")
      (ui/press-delete! stage)
      (when-not (ui/wait-for-element! stage :stock "Stock2")
        (fail! "Stock2 deleted while placement armed"))
      (pass! "delete-selection" "Delete ignored while placement armed")
      (ui/quit-app! stage)
      (pass! "delete-selection" "Quit requested"))))

(defn- run-select-objects! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1" :attempts 20)
        (fail! "Stock1 did not appear"))
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas [180 60])
      (when-not (ui/wait-for-element! stage :stock "Stock2" :attempts 20)
        (fail! "Stock2 did not appear"))
      (pass! "select-objects" "Stock1 and Stock2 placed")
      (ui/press-escape! stage)
      (ui/click-element! stage :stock "Stock1")
      (when-not (ui/element-selected? stage :stock "Stock1")
        (fail! "Stock1 not selected after click"))
      (when (ui/element-selected? stage :stock "Stock2")
        (fail! "Stock2 selected after Stock1 click"))
      (pass! "select-objects" "Plain click selects Stock1")
      (ui/click-element! stage :stock "Stock1")
      (when (ui/element-selected? stage :stock "Stock1")
        (fail! "Stock1 still selected after second click"))
      (pass! "select-objects" "Second click deselects Stock1")
      (ui/click-element! stage :stock "Stock1")
      (ui/shift-click-element! stage :stock "Stock2")
      (when-not (ui/element-selected? stage :stock "Stock1")
        (fail! "Stock1 not selected after shift-click add"))
      (when-not (ui/element-selected? stage :stock "Stock2")
        (fail! "Stock2 not selected after shift-click add"))
      (pass! "select-objects" "Shift-click adds Stock2 to selection")
      (ui/shift-click-element! stage :stock "Stock1")
      (when (ui/element-selected? stage :stock "Stock1")
        (fail! "Stock1 still selected after shift-click remove"))
      (when-not (ui/element-selected? stage :stock "Stock2")
        (fail! "Stock2 deselected after shift-click remove"))
      (pass! "select-objects" "Shift-click removes Stock1 from selection")
      (ui/marquee-select! stage :canvas [-120 -80] [80 80])
      (when-not (ui/element-selected? stage :stock "Stock1")
        (fail! "Stock1 not selected after marquee"))
      (when (ui/element-selected? stage :stock "Stock2")
        (fail! "Stock2 selected after marquee"))
      (pass! "select-objects" "Marquee selects intersecting Stock1 only")
      (ui/press-escape! stage)
      (when-not (ui/nothing-selected? stage)
        (fail! "Selection not cleared after Escape"))
      (pass! "select-objects" "Escape clears selection")
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (when (ui/element-selected? stage :stock "Stock1")
        (fail! "Stock1 selected while flow placement armed"))
      (pass! "select-objects" "Selection disabled while placement armed")
      (ui/quit-app! stage)
      (pass! "select-objects" "Quit requested"))))

(defn- run-control-panel! []
  (with-app! {}
    (fn [^Stage stage]
      (when-not (ui/region-bounds stage :control-panel)
        (fail! "Control panel region :control-panel is not visible"))
      (pass! "control-panel" "Control panel region is visible")
      (when-not (ui/step-button-visible? stage)
        (fail! "Step button not visible"))
      (pass! "control-panel" "Step button is visible")
      (when-not (ui/region-text-includes? stage :control-panel "0")
        (fail! "Simulation time 0 not visible in control panel"))
      (pass! "control-panel" "Simulation time 0 visible at start")
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :control-panel :center)
      (when-not (zero? (ui/diagram-stock-count stage))
        (fail! "Stock placed when clicking control panel with placement armed"))
      (pass! "control-panel" "Control panel click ignored during stock placement")
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1")
        (fail! "Stock1 did not appear"))
      (let [initial-bounds (ui/element-bounds stage :stock "Stock1")]
        (ui/drag-in-region! stage :control-panel :center [100 0])
        (Thread/sleep 300)
        (when-not (ui/bounds-unchanged? stage :stock "Stock1" initial-bounds)
          (fail! "Stock1 moved after drag within control panel"))
        (pass! "control-panel" "Stock drag ignored when pointer starts in control panel"))
      (ui/quit-app! stage)
      (pass! "control-panel" "Quit requested"))))

(defn- run-run-simulation! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Source")
      (ui/click-in-region! stage :canvas [-150 0])
      (when-not (ui/wait-for-element! stage :source "Source1")
        (fail! "Source1 did not appear"))
      (ui/click-palette! stage "Sink")
      (ui/click-in-region! stage :canvas [150 0])
      (when-not (ui/wait-for-element! stage :sink "Sink1")
        (fail! "Sink1 did not appear"))
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1")
        (fail! "Stock1 did not appear"))
      (pass! "run-simulation" "Source-stock-sink diagram placed")
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :source "Source1")
      (ui/click-element! stage :stock "Stock1")
      (assert-flow! stage "Flow1" "Source1" "Stock1"
                    :suite "run-simulation" :show-name? false)
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :stock "Stock1")
      (ui/click-element! stage :sink "Sink1")
      (assert-flow! stage "Flow2" "Stock1" "Sink1"
                    :suite "run-simulation" :show-name? false)
      (ui/right-click-element! stage :flow "Flow1")
      (when-not (ui/wait-for-dialog! "Edit Flow" :attempts 50)
        (fail! "Edit Flow dialog did not appear for Flow1"))
      (ui/type-into-dialog-field! "Rate" "10")
      (ui/click-ok-on-dialog! "Edit Flow")
      (when-not (ui/element-shows? stage :flow "Flow1" "10")
        (fail! "Flow1 rate not set to 10"))
      (ui/right-click-element! stage :flow "Flow2")
      (when-not (ui/wait-for-dialog! "Edit Flow")
        (fail! "Edit Flow dialog did not appear for Flow2"))
      (ui/type-into-dialog-field! "Rate" "5")
      (ui/click-ok-on-dialog! "Edit Flow")
      (when-not (ui/element-shows? stage :flow "Flow2" "5")
        (fail! "Flow2 rate not set to 5"))
      (pass! "run-simulation" "Flow rates set to 10 and 5")
      (when-not (ui/region-text-includes? stage :control-panel "0")
        (fail! "Simulation time 0 not visible before stepping"))
      (ui/click-step-button! stage)
      (when-not (ui/wait-for-region-text! stage :control-panel "0.1")
        (fail! "Simulation time 0.1 not visible after first Step"))
      (pass! "run-simulation" "First Step advanced time to 0.1")
      (ui/click-step-button! stage)
      (when-not (ui/wait-for-region-text! stage :control-panel "0.2")
        (fail! "Simulation time 0.2 not visible after second Step"))
      (pass! "run-simulation" "Second Step advanced time to 0.2")
      (ui/quit-app! stage)
      (pass! "run-simulation" "Quit requested"))))

(defn- click-step-n-times!
  [stage n]
  (dotimes [_ n]
    (ui/click-step-button! stage)))

(defn- run-fractional-flow-rate! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Source")
      (ui/click-in-region! stage :canvas [-150 0])
      (when-not (ui/wait-for-element! stage :source "Source1")
        (fail! "Source1 did not appear"))
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1")
        (fail! "Stock1 did not appear"))
      (ui/click-palette! stage "Flow")
      (ui/click-element! stage :source "Source1")
      (ui/click-element! stage :stock "Stock1")
      (assert-flow! stage "Flow1" "Source1" "Stock1"
                    :suite "fractional-flow-rate" :show-name? false)
      (ui/right-click-element! stage :flow "Flow1")
      (when-not (ui/wait-for-dialog! "Edit Flow" :attempts 50)
        (fail! "Edit Flow dialog did not appear"))
      (ui/type-into-dialog-field! "Rate" "0.1")
      (ui/click-ok-on-dialog! "Edit Flow")
      (when-not (ui/element-shows? stage :flow "Flow1" "0.1")
        (fail! "Flow1 rate not set to 0.1"))
      (pass! "fractional-flow-rate" "Flow1 rate set to 0.1")
      (when-not (ui/element-shows? stage :stock "Stock1" "0")
        (fail! "Stock1 value not 0 before stepping"))
      (pass! "fractional-flow-rate" "Stock1 value 0 before stepping")
      (click-step-n-times! stage 10)
      (when-not (ui/wait-for-region-text! stage :control-panel "1")
        (fail! "Simulation time not 1 after 10 steps"))
      (when-not (ui/wait-for-element-shows! stage :stock "Stock1" "0.1")
        (fail! "Stock1 value not 0.1 after 10 steps"))
      (pass! "fractional-flow-rate" "Stock1 value 0.1 after 10 steps")
      (click-step-n-times! stage 10)
      (when-not (ui/wait-for-region-text! stage :control-panel "2")
        (fail! "Simulation time not 2 after 20 steps"))
      (when-not (ui/wait-for-stock-label! "Stock1" "0.2" :attempts 50)
        (fail! "Stock1 value not 0.2 after 20 steps"))
      (pass! "fractional-flow-rate" "Stock1 value 0.2 after 20 steps")
      (ui/quit-app! stage)
      (pass! "fractional-flow-rate" "Quit requested"))))

(defn- run-stock-thermometer! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Stock")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :stock "Stock1" :attempts 20)
        (fail! "Stock1 did not appear"))
      (ui/right-click-element! stage :stock "Stock1")
      (when-not (ui/wait-for-dialog! "Edit Stock" :attempts 50)
        (fail! "Edit Stock dialog did not appear"))
      (ui/type-into-dialog-field! "Minimum" "0")
      (ui/type-into-dialog-field! "Maximum" "100")
      (ui/type-into-dialog-field! "Initial value" "0")
      (ui/click-ok-on-dialog! "Edit Stock")
      (ui/sync-thermometer-fills!)
      (when-not (ui/element-shows? stage :stock "Stock1" "Stock1")
        (fail! "Stock1 name not visible at top"))
      (when-not (ui/element-shows? stage :stock "Stock1" "0")
        (fail! "Stock1 minimum not visible"))
      (when-not (ui/element-shows? stage :stock "Stock1" "100")
        (fail! "Stock1 maximum not visible"))
      (pass! "stock-thermometer" "Stock1 name and bounds visible")
      (let [zero-fill (or (ui/thermometer-fill-width "Stock1") 0.0)]
        (when (> zero-fill 2.0)
          (fail! (str "Thermometer fill should be near empty at 0; width=" zero-fill))))
      (pass! "stock-thermometer" "Thermometer fill near empty at initial value 0")
      (ui/right-click-element! stage :stock "Stock1")
      (when-not (ui/wait-for-dialog! "Edit Stock")
        (fail! "Edit Stock dialog did not reappear"))
      (ui/type-into-dialog-field! "Initial value" "50")
      (ui/click-ok-on-dialog! "Edit Stock")
      (ui/sync-thermometer-fills!)
      (when-not (ui/wait-for-thermometer-fill-width! "Stock1" 30 42)
        (fail! "Thermometer fill not about half width at value 50"))
      (when-not (ui/thermometer-fill-light-blue? "Stock1")
        (fail! "Thermometer fill not light blue at value 50"))
      (let [half-width (ui/thermometer-fill-width "Stock1")]
        (pass! "stock-thermometer" "Thermometer fill about half width at value 50")
        (ui/click-palette! stage "Source")
        (ui/click-in-region! stage :canvas [-150 0])
        (when-not (ui/wait-for-element! stage :source "Source1")
          (fail! "Source1 did not appear"))
        (ui/click-palette! stage "Flow")
        (ui/click-element! stage :source "Source1")
        (ui/click-element! stage :stock "Stock1")
        (when-not (ui/wait-for-element! stage :flow "Flow1")
          (fail! "Flow1 did not appear"))
        (ui/press-escape! stage)
        (ui/right-click-element! stage :flow "Flow1")
        (when-not (ui/wait-for-dialog! "Edit Flow" :attempts 50)
          (fail! "Edit Flow dialog did not appear"))
        (ui/type-into-dialog-field! "Rate" "10")
        (ui/click-ok-on-dialog! "Edit Flow")
        (ui/click-step-button! stage)
        (when-not (ui/wait-for-thermometer-fill-width! "Stock1" (inc half-width) 72)
          (fail! (str "Thermometer fill did not grow after Step; half=" half-width
                      " now=" (ui/thermometer-fill-width "Stock1"))))
        (pass! "stock-thermometer" "Thermometer fill grew after simulation Step"))
      (ui/quit-app! stage)
      (pass! "stock-thermometer" "Quit requested"))))

(defn- run-drag-converter! []
  (with-app! {}
    (fn [^Stage stage]
      (ui/click-palette! stage "Converter")
      (ui/click-in-region! stage :canvas :center)
      (when-not (ui/wait-for-element! stage :converter "Converter1" :attempts 20)
        (fail! "Converter1 did not appear"))
      (ui/press-escape! stage)
      (let [initial-bounds (ui/element-bounds stage :converter "Converter1")]
        (ui/drag-element! stage :converter "Converter1" :canvas [100 80])
        (when-not (ui/wait-for-bounds-change! stage :converter "Converter1" initial-bounds :attempts 20)
          (fail! "Converter1 bounds did not change after drag"))
        (when-not (ui/element-visible? stage :converter "Converter1")
          (fail! "Converter1 not visible after drag"))
        (when-not (= 1 (ui/diagram-converter-count stage))
          (fail! "Expected exactly one converter after drag"))
        (pass! "drag-converter" "Converter1 dragged to new position")
        (place-two-stocks! stage)
        (ui/click-palette! stage "Flow")
        (ui/click-element! stage :stock "Stock1")
        (ui/click-element! stage :stock "Stock2")
        (assert-flow! stage "Flow1" "Stock1" "Stock2" :show-name? false)
        (ui/click-palette! stage "Connector")
        (ui/click-element! stage :converter "Converter1")
        (ui/click-element! stage :flow "Flow1")
        (when-not (ui/wait-for-element! stage :connector "Connector1" :attempts 20)
          (fail! "Connector1 did not appear"))
        (pass! "drag-converter" "Connector1 links Converter1 to Flow1")
        (ui/press-escape! stage)
        (ui/drag-element! stage :converter "Converter1" :canvas [-40 120])
        (Thread/sleep 300)
        (when-not (ui/element-visible? stage :connector "Connector1")
          (fail! "Connector1 missing after Converter1 drag"))
        (when-not (ui/connector-directed? stage :converter "Converter1" :flow "Flow1")
          (fail! "Connector1 not directed from Converter1 to Flow1 after drag"))
        (pass! "drag-converter" "Connector follows dragged Converter1")
        (ui/click-palette! stage "Converter")
        (ui/click-in-region! stage :canvas [220 60])
        (when-not (ui/wait-for-element! stage :converter "Converter2" :attempts 20)
          (fail! "Converter2 did not appear"))
        (when-not (ui/element-visible? stage :converter "Converter2")
          (fail! "Converter2 not visible"))
        (pass! "drag-converter" "Converter2 placed separately")
        (ui/click-palette! stage "Converter")
        (let [conv2-before (ui/element-bounds stage :converter "Converter2")]
          (ui/drag-element! stage :converter "Converter2" :canvas :center)
          (Thread/sleep 300)
          (when-not (ui/bounds-unchanged? stage :converter "Converter2" conv2-before)
            (fail! "Converter2 moved while placement tool armed"))
          (pass! "drag-converter" "Drag disabled while placement armed"))
        (ui/quit-app! stage)
        (pass! "drag-converter" "Quit requested")))))

(def ^:private suites
  {"qa-auto-close" run-qa-auto-close!
   "shell-launch" run-shell-launch!
   "shell-menus" run-shell-menus!
   "shell-about" run-shell-about!
   "shell-resize" run-shell-resize!
   "shell-quit" run-shell-quit!
   "place-stock" run-place-stock!
   "connect-flow" run-connect-flow!
   "cloud-palette" run-cloud-palette!
   "cloud-endpoints" run-cloud-endpoints!
   "connectors" run-connectors!
   "edit-stock" run-edit-stock!
   "edit-flow" run-edit-flow!
   "edit-converter" run-edit-converter!
   "drag-stock" run-drag-stock!
   "drag-converter" run-drag-converter!
   "select-objects" run-select-objects!
   "delete-selection" run-delete-selection!
   "control-panel" run-control-panel!
   "run-simulation" run-run-simulation!
   "fractional-flow-rate" run-fractional-flow-rate!
   "stock-thermometer" run-stock-thermometer!})

(defn -main [& args]
  (let [{:keys [qa-seconds args]} (qa-args/parse-qa-flag args)
        suite (first args)]
    (when qa-seconds
      (System/setProperty "stella.qa.auto-close-seconds" (str qa-seconds)))
    (when (qa-args/parse-debug-flag args)
      (System/setProperty "stella.debug" "true"))
    (when-not suite
      (fail! "Usage: clojure -M:qa [--qa <seconds>] [--debug] <suite-name>"))
    (try
      (if-let [run (get suites suite)]
        (run-suite! suite (fn [] (run)))
        (fail! (str "Unknown suite: " suite)))
      (finally
        (qa-auto-close/force-exit!)))))